language: php

php:
  - 8.1
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

before_script:
  - composer install

script: ./vendor/bin/phpunit --configuration phpunit.xml